/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menorcaminhofecea3;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author W7
 */
public class AboutMenu extends javax.swing.JFrame {

    /**
     * Creates new form AboutMenu
     */
    public AboutMenu() {
        initComponents();
        Centralize();
    }
  public void Centralize() {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 130, 40));

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("ABOUT"));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setTabSize(10);
        jTextArea1.setText("The Faculdade Estadual de Ciências Econônicas de Apucarana (FECEA) was founded in 1959. On February 16, 1961, \nthe college entrance exam began with a written test and oral test. On March 18, 1961, the inaugural class of \nthe first year of operation of the Faculty was held in the noble hall of the Nile Cairo State College. The lecture \nwas given by Professor Moacir Fantini who spoke on the theme \"The function of the Faculdade de Ciências Econômicas\nbefore the Brazilian reality\".In 2013, it joined one of the 7 UNESPAR campus.\nThe Universidade do Estado do Paraná (University of the State of Paraná  (Unespar) is an institution of higher\neducation administered by the Government of the Paraná State. This is a university that has campus all over the \nParaná State, in cities that have cultural and historical roots as different as Apucarana, Campo Mourão, Curitiba, \nParanaguá, Paranavaí, and União da Vitória. Despite the challenges that every multi-campi institution encounters,\nUnespar is one of the most integrated universities of Southern Brazil.\nUnespar offers undergraduate (bachelor's degree and teacher-training courses) and graduate courses (masters degree)\nin different fields of knowledge. Our teaching staff is comprised of more than 600 professionals that work hard to\nbring out the best in all of our students.\nThe core values of the Unespar is the pursuit and promotion of citizenship, democracy, cultural diversity, \nsustainable behaviour, and human development. It has as mission offer an environment for the development and \ndissemination of innovative knowledge in fields such as Sciences, Arts and Technology.\n\n\n\nThe project was created by the 2nd year of Computer Science students Guilherme Henrique de Souza and Sara Saori \nSatake in 2017, for the subject of Graph Teory.");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
